# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [6]:
### [your code here]
np.__version__

'2.0.2'

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [8]:
### [your code here]
a = np.random.random((2,3,5))
a

array([[[0.15711969, 0.95401039, 0.76470825, 0.01256763, 0.73201539],
        [0.10231945, 0.12628729, 0.71223011, 0.15453027, 0.42426859],
        [0.10093457, 0.91480494, 0.43289592, 0.03684499, 0.41659316]],

       [[0.78138684, 0.50916978, 0.52301017, 0.09932507, 0.1323062 ],
        [0.09319819, 0.93042777, 0.52109408, 0.11986289, 0.43294828],
        [0.82793162, 0.57546043, 0.58892916, 0.71631755, 0.12486098]]])

In [10]:
a = np.random.randint(3, size=((2,3,5)))
a

array([[[1, 1, 1, 1, 2],
        [0, 1, 0, 2, 1],
        [2, 0, 2, 1, 2]],

       [[2, 2, 0, 0, 0],
        [0, 2, 2, 0, 0],
        [2, 0, 2, 2, 2]]])


### 4. Print a.


In [11]:
### [your code here]
a

array([[[1, 1, 1, 1, 2],
        [0, 1, 0, 2, 1],
        [2, 0, 2, 1, 2]],

       [[2, 2, 0, 0, 0],
        [0, 2, 2, 0, 0],
        [2, 0, 2, 2, 2]]])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [13]:
### [your code here]
b = np.ones((5,2,3))


### 6. Print b.


In [14]:
### [your code here]
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [15]:
### [your code here]
a.size == b.size

True


### 8. Are you able to add a and b? Why or why not?


In [32]:
### [your code here]
# a + b

print(f"a.shape {a.shape}")
# print(f"a.ndim {a.ndim}")
print(f"b.shape {b.shape}")
# print(f"b.ndim {b.ndim}")

a.shape (2, 3, 5)
b.shape (5, 2, 3)




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [42]:
### [your code here]
c = np.transpose(b, axes=(1,2,0))
# print(a.shape)
# print(b.shape)
# print(f"c.shape {c.shape}")

array([[[2., 2., 2., 2., 3.],
        [1., 2., 1., 3., 2.],
        [3., 1., 3., 2., 3.]],

       [[3., 3., 1., 1., 1.],
        [1., 3., 3., 1., 1.],
        [3., 1., 3., 3., 3.]]])


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [43]:
### [your code here]
d = a + c
d

array([[[2., 2., 2., 2., 3.],
        [1., 2., 1., 3., 2.],
        [3., 1., 3., 2., 3.]],

       [[3., 3., 1., 1., 1.],
        [1., 3., 3., 1., 1.],
        [3., 1., 3., 3., 3.]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [45]:
### [your code here]
print(a.dtype)
print(d.dtype)


int64
float64



### 12. Multiply a and c. Assign the result to e.


In [47]:
### [your code here]
e = a * d
e

array([[[2., 2., 2., 2., 6.],
        [0., 2., 0., 6., 2.],
        [6., 0., 6., 2., 6.]],

       [[6., 6., 0., 0., 0.],
        [0., 6., 6., 0., 0.],
        [6., 0., 6., 6., 6.]]])



### 13. Does e equal to a? Why or why not?


In [48]:
### [your code here]
e == a
# zero values match but post multiplication the int converted to float64

array([[[False, False, False, False, False],
        [ True, False,  True, False, False],
        [False,  True, False, False, False]],

       [[False, False,  True,  True,  True],
        [ True, False, False,  True,  True],
        [False,  True, False, False, False]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [51]:
### [your code here]
d_min = np.min(d)
d_max = np.max(d)
d_mean = np.mean(d)

In [52]:
d_min

np.float64(1.0)

In [60]:
d_max

np.float64(3.0)

In [54]:
d_mean

np.float64(2.1)


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [62]:
### [your code here]
f = np.empty((2,3,5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [66]:
### [your code here]
# f = [0 if c == d_min else 25 if d_min < c < d_mean else 50 if d_mean == c else 75 if d_mean < c < d_max else 100 if d_max == c for a in d for b in a for c in b]

for i in range(len(d)):
  for j in range(len(d[i])):
    for k in range(len(d[i][j])):
      val = 0
      if d[i][j][k] == d_min:
        f[i][j][k] = 0
      elif d_min < d[i][j][k] < d_mean:
        f[i][j][k] = 25
      elif d_mean == d[i][j][k]:
        f[i][j][k] = 50
      elif d_mean < d[i][j][k] < d_max:
        f[i][j][k] = 75
      elif d_max == d[i][j][k]:
        f[i][j][k] = 100

f

array([[[ 25.,  25.,  25.,  25., 100.],
        [  0.,  25.,   0., 100.,  25.],
        [100.,   0., 100.,  25., 100.]],

       [[100., 100.,   0.,   0.,   0.],
        [  0., 100., 100.,   0.,   0.],
        [100.,   0., 100., 100., 100.]]])





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [72]:
### [your code here]
print(d)

print("#"*40)

print(f.astype(int))

[[[2. 2. 2. 2. 3.]
  [1. 2. 1. 3. 2.]
  [3. 1. 3. 2. 3.]]

 [[3. 3. 1. 1. 1.]
  [1. 3. 3. 1. 1.]
  [3. 1. 3. 3. 3.]]]
########################################
[[[ 25  25  25  25 100]
  [  0  25   0 100  25]
  [100   0 100  25 100]]

 [[100 100   0   0   0]
  [  0 100 100   0   0]
  [100   0 100 100 100]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [76]:
### [your code here]
f_copy = f.copy()
f_copy = f_copy.astype(str)

for i in range(len(f)):
  for j in range(len(f[i])):
    for k in range(len(f[i][j])):
      if f[i][j][k] == 0:
        f_copy[i][j][k] = "A"
      elif f[i][j][k] == 25:
        f_copy[i][j][k] = "B"
      elif f[i][j][k] == 50:
        f_copy[i][j][k] = "C"
      elif f[i][j][k] == 75:
        f_copy[i][j][k] = "D"
      elif f[i][j][k] == 100:
        f_copy[i][j][k] = "E"

f_copy

array([[['B', 'B', 'B', 'B', 'E'],
        ['A', 'B', 'A', 'E', 'B'],
        ['E', 'A', 'E', 'B', 'E']],

       [['E', 'E', 'A', 'A', 'A'],
        ['A', 'E', 'E', 'A', 'A'],
        ['E', 'A', 'E', 'E', 'E']]], dtype='<U32')